### ISSUE TITLE
Redirecting (302) to Docker network IP

### ISSUE THREAD

**Issue by TomFaulkner** [wallabag/docker#104]
I'm using a Docker bridge to set an IP address to proxy through Caddyserver. Unfortunately, when connecting to wallabag.domain.com Wallabag returns a 302 redirect to the docker static IP.

I tried including `SYMFONY__ENV__DOMAIN_NAME`, but this hasn't fixed the redirect. I'm probably doing something wrong, but I don't know what. Help would be appreciated.
```
docker run --restart always --name wallabag-db -e "POSTGRES_PASSWORD=password1" -e "POSTGRES_USER=pgauser" -v /root/wallabag/pg:/var/lib/postgresql/data -d postgres:9.6

docker run --name wallabag --restart always --link wallabag-db:wallabag-db -e "POSTGRES_PASSWORD=password1" -e "POSTGRES_USER=pgauser" -e "SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql" -e "SYMFONY__ENV__DATABASE_HOST=wallabag-db" -e "SYMFONY__ENV__DATABASE_PORT=5432" -e "SYMFONY__ENV__DATABASE_NAME=wallabag" -e "SYMFONY__ENV__DATABASE_USER=wallabag" -e "SYMFONY__ENV__DATABASE_PASSWORD=wallapass" -e "SYMFONY__ENV__DOMAIN_NAME=wallabag.domain.com" --net mynet --ip 172.18.0.3 wallabag/wallabag &
```

In the logs below, 172.18.0.250 is the Caddyserver proxy.

Logs:
```
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
PLAY [localhost] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var TASK [Gathering Facts] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [needed dirs] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var ok: [localhost] => (item=/var/www/wallabag/app) ok: [localhost] => (item=/var/www/wallabag/app/config) ok: [localhost] => (item=/var/www/wallabag/data) changed: [localhost] => (item=/var/www/wallabag/data/assets) ok: [localhost] => (item=/var/www/wallabag/data/db) TASK [write parameters.yml] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var changed: [localhost] TASK [stat] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [notify install for sqlite] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [wait for db container] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for wallabag-db:5432"} RUNNING HANDLER [chown dir] bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var to retry, use: --limit @/etc/ansible/entrypoint.retry PLAY RECAP bin dev entrypoint.sh etc home lib media mnt proc root run sbin srv sys tmp usr var localhost : ok=3 changed=2 unreachable=0 failed=1
Provisioner finished.
2018/02/10 02:11:23 [error] 212#212: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_craue_config_setting in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('SELECT t0.secti...', Array)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.secti...')
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.secti...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(196): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(73): Doctrine\ORM\EntityRepository->findOneBy(Array)
#5 /var/www/wallabag/ven" while reading response header from upstream, client: 172.18.0.250, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.18.0.3"
172.18.0.250 - - [10/Feb/2018:02:11:23 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4"
172.18.0.250 - - [10/Feb/2018:02:11:58 +0000] "GET / HTTP/1.1" 302 206 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0.4 Waterfox/56.0.4"
172.18.0.250 - - [10/Feb/2018:02:26:42 +0000] "GET / HTTP/1.1" 302 206 "-" "Mozilla/4.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/5.0)"
```

**Comment by ataraxus** [comment]
got bitten by this issue today. Setup is traefic + docker

**Comment by ataraxus** [comment]
I've fixed for me, despite not happy with the solution it doesn't redirect anymore. what was missing is a configuration in the config.yml: 

```
   # the IP address (or range) of your proxy
    trusted_proxies: [TRAEFIC_IP]
```

**Comment by ataraxus** [comment]
Ah, this does also work!
 docker-compose.yml: 

```
 environment:
      - TRUSTED_PROXIES=10.0.0.0/8,192.168.0.0/16
```
