### ISSUE TITLE
Problem install with docker and postgesql

### ISSUE THREAD

**Issue by s79dev** [wallabag/docker#114]
Try install wallabag on docker and postgresql
In postgresql, create database "wallabag", special user "wallabag", password "12345" , connect:
    `psql -U wallabag -d wallabag -h localhost`
get connect Ok
Start wallabag docker command:
```
 docker run -it --rm \
            -v ~/DockerData/Wallabag/postgre/data:/var/www/wallabag/data \
            -v ~/DockerData/Wallabag/postgre/images:/var/www/wallabag/web/assets/images \
            -v ~/DockerData/Wallabag/graby-site-config:/var/www/wallabag/vendor/j0k3r/graby-site-config \
            -v ~/DockerData/Wallabag/postgre/export:/export \
            -v ~/DockerData/Wallabag/postgre/log:/var/log \
            -e SYMFONY__ENV__FOSUSER_REGISTRATION=false -e SYMFONY_ENV=dev \
            -e SYMFONY__ENV__DOMAIN_NAME="..." \
            -e SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql \
            -e POSTGRES_USER=wallabag \
            -e SYMFONY__ENV__DATABASE_NAME=wallabag  \
            -e SYMFONY__ENV__DATABASE_USER=wallabag  \
            -e POSTGRES_PASSWORD=12345  \
            -e SYMFONY__ENV__DATABASE_HOST=172.17.0.1 \
            -e SYMFONY__ENV__DATABASE_PORT=5432 \
           -e SYMFONY__ENV__DATABASE_DRIVER_CLASS="Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver" \
            -p 8080:80  wallabag/wallabag
```
get 
```
    Starting provisioner...
     [WARNING]: Found both group and host with same name: localhost
     Provisioner finished.
     [17-Jun-2018 09:32:00] NOTICE: fpm is running, pid 230
     [17-Jun-2018 09:32:00] NOTICE: ready to handle connections
```
try connect from browser and got blank page and error in log:
   ```
 2018/06/17 09:44:37 [error] 231#231: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] fe_sendauth: no password supplied in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
    Stack trace:
    #0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('pgsql:host=172....', 'wallabag', NULL, Array)
    #1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('pgsql:host=172....', 'wallabag', NULL, Array)
    #2 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOPgSql\Driver->connect(Array, 'wallabag', NULL, Array)
    #3 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Connection->connect()
    #4 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.secti...', Array, Array)
    #5 /var/www/" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /login HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "..."
```
and after, try connect 
   ` psql -U wallabag -d wallabag -h localhost`
get:
   ` psql: FATAL:  password authentication failed for user "wallabag"`

What wallabag do in base?

**Comment by danhimalplanet** [comment]
I got wallabag postgres working with the following docker-compose.yml

`version: '3.5'
volumes:
  wallabag-postgres-db:
    name: wallabag-postgres-db
services:
  wallabag:
    build:
      context: ../
    image: wallabag:postgresql
    container_name: wallabag
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret.root.password
      - SYMFONY__ENV__SECRET=F00B4R
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_DRIVER_CLASS=Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=secret.password
      - SYMFONY__ENV__DOMAIN_NAME="https://amazing.wallabag.instance"
      - SYMFONY__ENV__MAILER_HOST="my.mail.server"
      - SYMFONY__ENV__MAILER_USER="email@mail.server"
      - SYMFONY__ENV__MAILER_PASSWORD="wOjGNcF0yi"
      - SYMFONY__ENV__FROM_EMAIL="email@mail.server"
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    ports:
      - 80
    depends_on:
      - db
  db:
    container_name: wallabag_db
    image: postgres:10.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret.root.password
    volumes:
      - wallabag-postgres-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro`

**Comment by luckydonald** [comment]
I got the same error.

In fact, having some environment variable missing causes huge errors.

The note about `make sure you include http/https when setting ENV__DOMAIN_NAME` was important to.

If you mess up anything, drop the database and restart. It doesn't recovers well.

And yes, you need to expose your root database password to the container... *\*sigh\**

While trying to solve that, I also stumbled over:
https://github.com/wallabag/wallabag/issues/3577#issuecomment-363576511
https://github.com/wallabag/wallabag/issues/3662
https://github.com/wallabag/wallabag/issues/3682
