### ISSUE TITLE
Setting FOSUSER_CONFIRMATION to false breaks wallabag

### ISSUE THREAD

**Issue by LukasWerfel** [wallabag/docker#143]
Whenever I set FOSUSER_CONFIRMATION to false it breaks wallabag.
```
wallabag     | 2019/01/13 14:43:43 [error] 201#201: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to write in the cache directory (/var/www/wallabag/var/cache/prod)
wallabag     |  in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:676
wallabag     | Stack trace:
wallabag     | #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(573): Symfony\Component\HttpKernel\Kernel->buildContainer()
wallabag     | #1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(117): Symfony\Component\HttpKernel\Kernel->initializeContainer()
wallabag     | #2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(166): Symfony\Component\HttpKernel\Kernel->boot()
wallabag     | #3 /var/www/wallabag/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
wallabag     | #4 {main}
wallabag     |   thrown in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 676" while reading response header from upstream, client: 10.1.1.1, server: _, request: "GET / HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "wb.domain.eu"
wallabag     | 10.1.1.1 - - [13/Jan/2019:14:43:43 +0000] "GET / HTTP/1.0" 500 20 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
```

[My compose file](https://github.com/LukasWerfel/server-setup/blob/master/docker-compose-local.yml#L22-L32)

**Comment by LukasWerfel** [comment]
The issue was that I set it as a string and not as a boolean 
```
SYMFONY__ENV__FOSUSER_CONFIRMATION="false" # wrong
```
```
SYMFONY__ENV__FOSUSER_CONFIRMATION="false" # correct
```
