### ISSUE TITLE
Can't get Wallabag to start :(

### ISSUE THREAD

**Issue by aashish108** [wallabag/docker#182]
Hello :) Been trying out Wallabag as it looks amazing, thing is its not working. I use the recommended docker-compose file and that should ideally be it. That didn't work, so then I ran the migration docker commands, it seemed to work successfully; restarted Wallabag but still no joy. Here are the logs.

Any help much appreciated pls :)

```
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
PLAY [localhost] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var TASK [Gathering Facts] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [needed dirs] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] => (item=/var/www/wallabag/app) ok: [localhost] => (item=/var/www/wallabag/app/config) ok: [localhost] => (item=/var/www/wallabag/data) ok: [localhost] => (item=/var/www/wallabag/data/assets) ok: [localhost] => (item=/var/www/wallabag/data/db) TASK [write parameters.yml] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [stat] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [notify install for sqlite] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [wait for db container] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for db:3306"} PLAY RECAP bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var localhost : ok=3 changed=0 unreachable=0 failed=1 skipped=2 rescued=0 ignored=0
Provisioner finished.
2020/02/14 10:16:14 [error] 156#156: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665PHP message: PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182
Stack trace:
#0 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(77): Craue\ConfigBundle\Util\Config->createNotFoundException('piwik_enabled')
#1 /var/www/wallabag/vendor/craue/config-bundle/Twig/Extension/ConfigTemplateExtension.php(96): Craue\ConfigBundle\Util\Config->get('piwik_enabled')
172.21.0.1 - - [14/Feb/2020:10:16:14 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.131 Safari/537.36"
#2 /var/www/wallabag/var/cache/prod/twig/e5/e59b3c6ba046bc5541ec427c6fe013ac603e567122ed934d6dc17178083d1b89.php(96): Craue\ConfigBundle\Twig\Extension\ConfigTemplateExtension->getSetting('piwik_enabled')
#3 /var/www/wallabag/vendor/twig/twig/src/Template.php(443): __TwigTemplate_248ffdebaf41f0c401270de5135adaa2a06bcf1a73c1cf5c0f36284706bf3bb5->doDisplay(Array, Array)
#4 /var/www/wallabag/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/wallabag/var/cache/prod/twig/d9/d956e063b" while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.100:8383"
2020/02/14 10:20:31 [error] 156#156: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665PHP message: PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182
Stack trace:
#0 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(77): Craue\ConfigBundle\Util\Config->createNotFoundException('piwik_enabled')
#1 /var/www/wallabag/vendor/craue/config-bundle/Twig/Extension/ConfigTemplateExtension.php(96): Craue\ConfigBundle\Util\Config->get('piwik_enabled')
#2 /var/www/wallabag/var/cache/prod/twig/e5/e59b3c6ba046bc5541ec427c6fe013ac603e567122ed934d6dc17178083d1b89.php(96): Craue\ConfigBundle\Twig\Extension\ConfigTemplateExtension->getSetting('piwik_enabled')
#3 /var/www/wallabag/vendor/twig/twig/src/Template.php(443): __TwigTemplate_248ffdebaf41f0c401270de5135adaa2a06bcf1a73c1cf5c0f36284706bf3bb5->doDisplay(Array, Array)
#4 /var/www/wallabag/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/wallabag/var/cache/prod/twig/d9/d956e063b" while reading response header from upstream, client: 172.21.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.100:8383"
172.21.0.1 - - [14/Feb/2020:10:20:31 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.131 Safari/537.36"
2020/02/14 10:20:40 [error] 156#156: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665PHP message: PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182
Stack trace:
#0 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(77): Craue\ConfigBundle\Util\Config->createNotFoundException('piwik_enabled')
#1 /var/www/wallabag/vendor/craue/config-bundle/Twig/Extension/ConfigTemplateExtension.php(96): Craue\ConfigBundle\Util\Config->get('piwik_enabled')
#2 /var/www/wallabag/var/cache/prod/twig/e5/e59b3c6ba046bc5541ec427c6fe013ac603e567122ed934d6dc17178083d1b89.php(96): Craue\ConfigBundle\Twig\Extension\ConfigTemplateExtension->getSetting('piwik_enabled')
#3 /var/www/wallabag/vendor/twig/twig/src/Template.php(443): __TwigTemplate_248ffdebaf41f0c401270de5135adaa2a06bcf1a73c1cf5c0f36284706bf3bb5->doDisplay(Array, Array)
#4 /var/www/wallabag/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array)
#5 /var/www/wallabag/var/cache/prod/twig/d9/d956e063b" while reading response header from upstream, client: 192.168.0.100, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.domain.space"
192.168.0.100 - - [14/Feb/2020:10:20:40 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.131 Safari/537.36"
```

**Comment by bjschafer** [comment]
Apparently you also need to run the install command: `docker exec -t your-wallabag-container /var/www/wallabag/bin/console wallabag:install --env=prod --no-interaction`

**Comment by aashish108** [comment]
That didn't work. I can try again but looks like Wallabag cannot fly. Too complex a setup when I have several other docker services running.

**Comment by rYR79435** [comment]
> TASK [wait for db container] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for db:3306"}
From your log indicates that Wallabag can't reach your database.
I don't know what is up with the PHP errors, but they should be irrelavant (for now at least), since you don't even have a connection to your DB.

**Comment by stefandesu** [comment]
Thanks @bjschafer, that worked for me. Very weird that this is not documented in the Docker README. 🤔

**Comment by j0k3r** [comment]
Fix it by creating a PR 😉

**Comment by stefandesu** [comment]
You're right, but my personal opinion is that this shouldn't be necessary at all (it should be done automatically if necessary) and I don't have enough knowledge to make that work (nor do I know whether this is actually wanted by the maintainers).
