### ISSUE TITLE
Error after 2.4.0 update: Can't DROP FOREIGN KEY `IDX_user_oauth_client`

### ISSUE THREAD

**Issue by somedevreally** [wallabag/docker#226]
I have docker container `wallabag/wallabag` after updating to 2.4.0  wallabag wont start.
```

Starting provisioner...

[WARNING]: Found both group and host with same name: localhost

[WARNING]: Platform linux on host localhost is using the discovered Python

interpreter at /usr/bin/python3, but future installation of another Python

interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen

ce_appendices/interpreter_discovery.html for more information.

Provisioner finished.

172.25.0.13 - - [10/Dec/2020:15:37:00 +0000] "POST /oauth/v2/token HTTP/1.1" 200 275 "-" "-"

2020/12/10 15:48:48 [error] 243#243: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: t0.googleAuthenticatorSecret in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67


Stack trace:

#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(67): PDO->prepare('SELECT t0.usern...', Array)

#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(903): Doctrine\DBAL\Driver\PDOConnection->prepare('SELECT t0.usern...')

#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.usern...', Array, Array)

#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)

#4 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Doctrine/UserManager.php(84): Doctrine\ORM\EntityRepository->findOneBy(Array" while reading response header from upstream, client: 172.25.0.2, server: _, request: "POST /oauth/v2/token HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.sun"

172.25.0.2 - - [10/Dec/2020:15:48:48 +0000] "POST /oauth/v2/token HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

172.25.0.2 - - [10/Dec/2020:15:51:47 +0000] "GET / HTTP/1.1" 302 209 "http://heimdall.sun/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

2020/12/10 15:51:48 [error] 243#243: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: wallabag_internal_setting in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:67
```

**Comment by j0k3r** [comment]
Have you read https://github.com/wallabag/docker#upgrading?

**Comment by bnjbvr** [comment]
Guess I should have read the manual too :innocent: That being said, I'm now running into a migration error.

<details>

```
  ++ migrating 20190510141130

     -> ALTER TABLE `wallabag_oauth2_access_tokens` DROP FOREIGN KEY FK_368A4209A76ED395
     -> ALTER TABLE `wallabag_oauth2_access_tokens` ADD CONSTRAINT FK_368A4209A76ED395 FOREIGN KEY (user_id) REFERENCES `wallabag_user` (id) ON DELETE CASCADE
     -> ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client
Migration 20190510141130 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'IDX_user_oauth_client'; check that column/key exists
16:11:19 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --env=prod --no-interaction". Message: "An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'IDX_user_oauth_client'; check that column/key exists" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate --env=prod --no-interaction","message" => """  An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'IDX_user_oauth_client'; check that column/key exists  """]

In AbstractMySQLDriver.php line 110:
                                                               
  An exception occurred while executing 'ALTER TABLE `wallaba  
  g_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':   
                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can  
  't DROP 'IDX_user_oauth_client'; check that column/key exis  
  ts                                                           
                                                               

In PDOConnection.php line 91:
                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can  
  't DROP 'IDX_user_oauth_client'; check that column/key exis  
  ts                                                           
                                                               

In PDOConnection.php line 86:
                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can  
  't DROP 'IDX_user_oauth_client'; check that column/key exis  
  ts                                                           
 ```

</details>

**Comment by somedevreally** [comment]
running this command resolved the issue, thanks

`$ docker exec -t NAME_OR_ID_OF_YOUR_WALLABAG_CONTAINER /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction`

**Comment by bnjbvr** [comment]
> That being said, I'm now running into a migration error.

I sorted it out by recreating the missing foreign key constraint by reading the code of the migration that introduced it, and it worked normally. Please don't mind me :)

**Comment by j0k3r** [comment]
@bnjbvr I'm late but I wanted to know which foreign key constraints were defined in that table `wallabag_oauth2_clients` to better understand why it's not the one defined in the migration and maybe update the migration to use that _new_ key

**Comment by bnjbvr** [comment]
> @bnjbvr I'm late but I wanted to know which foreign key constraints were defined in that table wallabag_oauth2_clients to better understand why it's not the one defined in the migration and maybe update the migration to use that new key

I ran into errors related to the `IDX_user_oauth_client` foreign key being missing. (My install uses a mysql database, fwiw.)
I am not sure how I ran into this. Maybe a migration partially failed, and the `down` function didn't recreate the foreign key it just dropped? In any case, I hadn't ran migrations for at least a year, so I was probably in a bad setup in the first place.

**Comment by j0k3r** [comment]
I was asking because you were not the only to get that error: https://gitter.im/wallabag/wallabag?at=5fd2698a0697c1210db31099

**Comment by bnjbvr** [comment]
Interesting; I remember re-adding the foreign constraint manually, and then removing another one that was present twice, one of the FK_6... foreign keys.

**Comment by ddeimeke** [comment]
I am facing the same error.

php-Version: 7.3.25
MariaDB: 10.5.8

on CentOS 7

Wallabag installed via Git repository and `sudo -u apache make update`.

**Comment by markwaters** [comment]
Greeting everyone.
I was / am running 2.3.8 on a VPS using MariaDB and NGINX.
Enthusiastically ran the 'make update' script.
The upgrade was successful until this part.

```
Migrating up to 20200428072628 from 20190425115043

  ++ migrating 20190510141130

     -> ALTER TABLE `wallabag_oauth2_access_tokens` DROP FOREIGN KEY FK_368A4209A76ED395
     -> ALTER TABLE `wallabag_oauth2_access_tokens` ADD CONSTRAINT FK_368A4209A76ED395 FOREIGN KEY (user_id) REFERENCES `wallabag_user` (id) ON DELETE CASCADE
     -> ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client
Migration 20190510141130 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `IDX_user_oauth_client`; check that it exists
11:58:25 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --no-interaction --env=prod". Message: "An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `IDX_user_oauth_client`; check that it exists" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "doctrine:migrations:migrate --no-interaction --env=prod","message" => """  An exception occurred while executing 'ALTER TABLE `wallabag_oauth2_clients` DROP FOREIGN KEY IDX_user_oauth_client':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `IDX_user_oauth_client`; check that it exists  """]

```
I would appreciate any suggestions about how to get it running again.
Thanks.
Mark.

**Comment by j0k3r** [comment]
@ddeimeke @markwaters Which foreign key constraints are defined in that table `wallabag_oauth2_clients`?
It's to better understand why it's not the one defined in the migration and maybe update the migration to use that new key

**Comment by Zayon** [comment]
Sorry for that PMA screenshot but hopefully it gives you the information you need.

![image](https://user-images.githubusercontent.com/3958468/101898374-5025cb80-3bac-11eb-80cd-c79c79fdddf5.png)

**Comment by bnjbvr** [comment]
Here you go: the IDX_635 was the one i described in the second part and had to remove by hand, in addition to re-adding the first foreign key so the whole migration works again.

**Comment by ddeimeke** [comment]
> @ddeimeke @markwaters Which foreign key constraints are defined in that table `wallabag_oauth2_clients`?
> It's to better understand why it's not the one defined in the migration and maybe update the migration to use that new key

Is that ok for you? I grepped the information from my backup:

```
# grep CONSTRAINT wallabag*
wallabag.wallabag_annotation-schema.sql:  CONSTRAINT `FK_A7AED006A76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`),
wallabag.wallabag_annotation-schema.sql:  CONSTRAINT `FK_annotation_entry` FOREIGN KEY (`entry_id`) REFERENCES `wallabag_entry` (`id`) ON DELETE CASCADE
wallabag.wallabag_config-schema.sql:  CONSTRAINT `FK_87E64C53A76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_entry-schema.sql:  CONSTRAINT `FK_F4D18282A76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_entry_tag-schema.sql:  CONSTRAINT `FK_entry_tag_entry` FOREIGN KEY (`entry_id`) REFERENCES `wallabag_entry` (`id`) ON DELETE CASCADE,
wallabag.wallabag_entry_tag-schema.sql:  CONSTRAINT `FK_entry_tag_tag` FOREIGN KEY (`tag_id`) REFERENCES `wallabag_tag` (`id`) ON DELETE CASCADE
wallabag.wallabag_oauth2_access_tokens-schema.sql:  CONSTRAINT `FK_368A420919EB6921` FOREIGN KEY (`client_id`) REFERENCES `wallabag_oauth2_clients` (`id`),
wallabag.wallabag_oauth2_access_tokens-schema.sql:  CONSTRAINT `FK_368A4209A76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_oauth2_auth_codes-schema.sql:  CONSTRAINT `FK_EE52E3FA19EB6921` FOREIGN KEY (`client_id`) REFERENCES `wallabag_oauth2_clients` (`id`),
wallabag.wallabag_oauth2_auth_codes-schema.sql:  CONSTRAINT `FK_EE52E3FAA76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_oauth2_clients-schema.sql:  CONSTRAINT `FK_635D765EA76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_oauth2_refresh_tokens-schema.sql:  CONSTRAINT `FK_20C9FB2419EB6921` FOREIGN KEY (`client_id`) REFERENCES `wallabag_oauth2_clients` (`id`),
wallabag.wallabag_oauth2_refresh_tokens-schema.sql:  CONSTRAINT `FK_20C9FB24A76ED395` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_site_credential-schema.sql:  CONSTRAINT `fk_user` FOREIGN KEY (`user_id`) REFERENCES `wallabag_user` (`id`)
wallabag.wallabag_tagging_rule-schema.sql:  CONSTRAINT `FK_2D9B3C5424DB0683` FOREIGN KEY (`config_id`) REFERENCES `wallabag_config` (`id`)
```

If you need additional data please tell me.

**Comment by j0k3r** [comment]
Ok looks like it's a legit index which was added here https://github.com/wallabag/wallabag/blob/ac4fda6ae9dbe4abcff3bedc214b4b6a2c171050/app/DoctrineMigrations/Version20190510141130.php#L67-L68
I'm wondering why nothing popup during tests 🤔

We'll update the migration script to workaround that index.

**Comment by markwaters** [comment]
> Ok looks like it's a legit index which was added here https://github.com/wallabag/wallabag/blob/ac4fda6ae9dbe4abcff3bedc214b4b6a2c171050/app/DoctrineMigrations/Version20190510141130.php#L67-L68
> I'm wondering why nothing popup during tests 
> 
> We'll update the migration script to workaround that index.

Thank you.

**Comment by j0k3r** [comment]
I'll close the issue to keep focus on only one on the main repo.
Thanks for all these information folks.

Duplicates https://github.com/wallabag/wallabag/issues/4826
