### ISSUE TITLE
Not working: Installing Dockerized Wallabag on Traefik (+ Let's Encrypt Reverse Proxy)

### ISSUE THREAD

**Issue by kromsam** [wallabag/docker#296]
I am completely at a loss. I have been busy for almost the entire day to set up Wallabag using Traefik on my homeserver. I haven't been able to get Wallabag working at all, not even without Traefik. There are a lot's and issues concerning this topic on here, I used a lot of their tips but nothing worked. Therefore, I'll share my configuration and the steps I took, so that hopefully we can finally tackle this problem and be able to create a smooth and easy way to set up Wallabag on Docker.

### Relevant parts of Docker Compose
I tried to follow these instructions: https://github.com/wallabag/docker . I added `POPULATE_DATABASE=false` which was suggested on multiple places, like here: https://github.com/wallabag/docker/issues/170.

```
version: '3'
services:

# Traefik
  Traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA}/Traefik/traefik.yml:/traefik.yml
      - ${APPDATA}/Traefik/dynamic.yml:/dynamic.yml
      - ${APPDATA}/Traefik/acme.json:/acme.json
      - ${APPDATA}/Traefik/traefik.log:/traefik.log
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.traefik-secure.entrypoints: "websecure"
      traefik.http.routers.traefik-secure.rule: "Host(`${TTDOMAIN}`)"
      traefik.http.routers.traefik-secure.service: "api@internal"
      traefik.http.routers.traefik-secure.middlewares: "user-auth@file,secureHeaders@file"
    ports:
      - 82:80
      - 446:443
      - ${SSHPORT}:${SSHPORT}
    networks:
      - proxy
      - wallabag_net

# Wallabag
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${WB_DB_ROOT}
      - SYMFONY__ENV__DATABASE_DRIVER=${WB_DB_DRIVER}
      - SYMFONY__ENV__DATABASE_HOST=${WB_DB_HOST}
      - SYMFONY__ENV__DATABASE_PORT=${WB_DB_PORT}
      - SYMFONY__ENV__DATABASE_NAME=${WB_DB_NAME}
      - SYMFONY__ENV__DATABASE_USER=${WB_DB_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${WB_DB_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=${WB_MAIL_USER}
      - SYMFONY__ENV__MAILER_PASSWORD=${WB_MAIL_PASSWORD}
      - SYMFONY__ENV__FROM_EMAIL=${WB_MAIL_FROM}
      - SYMFONY__ENV__DOMAIN_NAME=https://${WB_DOMAIN}
      - SYMFONY__ENV__SERVER_NAME=${WB_NAME}
      - POPULATE_DATABASE=false
      - SYMFONY__ENV__FOSUSER_REGISTRATION=false
    networks:
      - wallabag_net
      - proxy
    volumes:
      - ${APPDATA}/Wallabag/config:/var/www/wallabag/web/assets/images
      - ${APPDATA}/Wallabag/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${APPDATA}/Wallabag/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - wallabag_db
      - wallabag_redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag-secure.entryPoints=websecure"
      - "traefik.http.routers.wallabag-secure.rule=Host(`${WB_DOMAIN}`)"
      - "traefik.http.routers.wallabag-secure.service=wallabag-svc"
      - "traefik.http.services.wallabag-svc.loadBalancer.server.port=80"
  wallabag_db:
    container_name: wallabag_db
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${WB_DB_ROOT}
      - MARIADB_DATABASE=${WB_DB_NAME}
      - MARIADB_USER=${WB_DB_USER}
      - MARIADB_PASSWORD=${WB_DB_PASSWORD}
    volumes:
      - ${APPDATA}/Wallabag/Wallabag_DB:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
    networks:
      - wallabag_net
  wallabag_redis:
    container_name: wallabag_redis
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    networks:
      - wallabag_net

networks:
  proxy:
    driver: bridge
    external: true
  wallabag_net:
    driver: bridge
```

### Some environment variables
```
WB_DB_DRIVER=pdo_mysql
WB_DB_HOST=wallabag_db
WB_DB_PORT=3306
```

The WB_DOMAIN is of the form `yadayada.domain.tld`.

### Changed nginx.conf & fastcgi_params
I implemented the changes suggested in this PR:  https://github.com/wallabag/docker/pull/265. So these files look like this:

nginx.conf
```
user  nginx;
worker_processes  1;
pid        /var/run/nginx.pid;

events {
    worker_connections  2048;
    multi_accept on;
    use epoll;
}

http {

    server_tokens off;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 15;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    error_log off;
    gzip on;
    gzip_disable "msie6";
    open_file_cache max=100;
    client_max_body_size 100M;

    map $http_x_forwarded_proto $fe_https {
        default $https;
        https on;
    }

    upstream php-upstream {
        server 127.0.0.1:9000;
    }

    server {
        listen 80;
        server_name _;
        root /var/www/wallabag/web;

        location / {
            # try to serve file directly, fallback to app.php
            try_files $uri /app.php$is_args$args;
        }

        location ~ ^/app\.php(/|$) {
            fastcgi_pass php-upstream;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            # When you are using symlinks to link the document root to the
            # current version of your application, you should pass the real
            # application path instead of the path to the symlink to PHP
            # FPM.
            # Otherwise, PHP's OPcache may not properly detect changes to
            # your PHP files (see https://github.com/zendtech/ZendOptimizerPlus/issues/126
            # for more information).
            fastcgi_param  SCRIPT_FILENAME  $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            # Prevents URIs that include the front controller. This will 404:
            # http://domain.tld/app.php/some-path
            # Remove the internal directive to allow URIs like this
            internal;
        }

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
    }

}

daemon off;
```

fastcgi_params:
```

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $fe_https;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param REDIRECT_STATUS 200;
```

### Time to run it

Here are the logs of the `wallabag_db` container:
```
2022-08-18 00:08:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.5+maria~focal started.
2022-08-18 00:08:31+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-18 00:08:31+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.5+maria~focal started.
2022-08-18 00:08:31+00:00 [Note] [Entrypoint]: Initializing database files
2022-08-18  0:08:32 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at https://mariadb.com/kb or the
MySQL manual for more instructions.

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.
You can find additional information about the MySQL part at:
https://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2022-08-18 00:09:38+00:00 [Note] [Entrypoint]: Database files initialized
2022-08-18 00:09:38+00:00 [Note] [Entrypoint]: Starting temporary server
2022-08-18 00:09:38+00:00 [Note] [Entrypoint]: Waiting for server startup
2022-08-18  0:09:38 0 [Note] mariadbd (server 10.6.5-MariaDB-1:10.6.5+maria~focal) starting as process 137 ...
2022-08-18  0:09:38 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-08-18  0:09:38 0 [Note] InnoDB: Number of pools: 1
2022-08-18  0:09:38 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-08-18  0:09:38 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-08-18  0:09:38 0 [Note] InnoDB: Using Linux native AIO
2022-08-18  0:09:38 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-08-18  0:09:38 0 [Note] InnoDB: Completed initialization of buffer pool
2022-08-18  0:09:39 0 [Note] InnoDB: 128 rollback segments are active.
2022-08-18  0:09:39 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-08-18  0:09:39 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-08-18  0:09:39 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-08-18  0:09:39 0 [Note] InnoDB: 10.6.5 started; log sequence number 42161; transaction id 14
2022-08-18  0:09:39 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-08-18  0:09:39 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-08-18  0:09:39 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-08-18  0:09:39 0 [Warning] 'user' entry 'root@2a5df0a4abe1' ignored in --skip-name-resolve mode.
2022-08-18  0:09:39 0 [Warning] 'proxies_priv' entry '@% root@2a5df0a4abe1' ignored in --skip-name-resolve mode.
2022-08-18  0:09:40 0 [Note] InnoDB: Buffer pool(s) load completed at 220818  0:09:40
2022-08-18  0:09:40 0 [Note] mariadbd: ready for connections.
Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2022-08-18 00:09:40+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2022-08-18  0:09:57 6 [Warning] 'proxies_priv' entry '@% root@2a5df0a4abe1' ignored in --skip-name-resolve mode.
2022-08-18 00:09:57+00:00 [Note] [Entrypoint]: Creating database wallabag
2022-08-18 00:09:57+00:00 [Note] [Entrypoint]: Creating user wallabag
2022-08-18 00:09:57+00:00 [Note] [Entrypoint]: Giving user wallabag access to schema wallabag

2022-08-18 00:09:57+00:00 [Note] [Entrypoint]: Stopping temporary server
2022-08-18  0:09:57 0 [Note] mariadbd (initiated by: root[root] @ localhost []): Normal shutdown
2022-08-18  0:09:57 0 [Note] InnoDB: FTS optimize thread exiting.
2022-08-18  0:09:58 0 [Note] InnoDB: Starting shutdown...
2022-08-18  0:09:58 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2022-08-18  0:09:58 0 [Note] InnoDB: Buffer pool(s) dump completed at 220818  0:09:58
2022-08-18  0:09:58 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2022-08-18  0:09:58 0 [Note] InnoDB: Shutdown completed; log sequence number 42173; transaction id 15
2022-08-18  0:09:58 0 [Note] mariadbd: Shutdown complete

2022-08-18 00:09:58+00:00 [Note] [Entrypoint]: Temporary server stopped

2022-08-18 00:09:58+00:00 [Note] [Entrypoint]: MariaDB init process done. Ready for start up.

2022-08-18  0:09:59 0 [Note] mariadbd (server 10.6.5-MariaDB-1:10.6.5+maria~focal) starting as process 1 ...
2022-08-18  0:09:59 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-08-18  0:09:59 0 [Note] InnoDB: Number of pools: 1
2022-08-18  0:09:59 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-08-18  0:09:59 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-08-18  0:09:59 0 [Note] InnoDB: Using Linux native AIO
2022-08-18  0:09:59 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-08-18  0:09:59 0 [Note] InnoDB: Completed initialization of buffer pool
2022-08-18  0:09:59 0 [Note] InnoDB: 128 rollback segments are active.
2022-08-18  0:09:59 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-08-18  0:09:59 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-08-18  0:09:59 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-08-18  0:09:59 0 [Note] InnoDB: 10.6.5 started; log sequence number 42173; transaction id 14
2022-08-18  0:09:59 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-08-18  0:09:59 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-08-18  0:09:59 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-08-18  0:09:59 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-08-18  0:09:59 0 [Note] Server socket created on IP: '::'.
2022-08-18  0:09:59 0 [Warning] 'proxies_priv' entry '@% root@2a5df0a4abe1' ignored in --skip-name-resolve mode.
2022-08-18  0:09:59 0 [Note] InnoDB: Buffer pool(s) load completed at 220818  0:09:59
2022-08-18  0:09:59 0 [Note] mariadbd: ready for connections.
Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2022-08-18  0:10:00 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.6' (This connection closed normally without authentication)
2022-08-18  0:10:11 6 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-08-18  0:10:31 7 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-08-18  0:10:51 10 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

Here are the logs of the `wallabag` container:
```
Starting provisioner...
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3.9, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.11/reference_appendices/interpreter_discovery.html for more information.
Provisioner finished.
127.0.0.1 - - [18/Aug/2022:00:10:32 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
2022/08/18 00:10:32 [error] 266#266: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_internal_setting' doesn't exist in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1304): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.value...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(73): Doctrine\ORM\EntityRepository->findOneBy(Array)
#5 /var/www/wallabag" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
127.0.0.1 - - [18/Aug/2022:00:10:32 +0000] "GET /login HTTP/1.1" 500 5 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:11:32 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
2022/08/18 00:11:33 [error] 266#266: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wallabag.wallabag_internal_setting' doesn't exist in /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
#1 /var/www/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1304): Doctrine\DBAL\Driver\PDOStatement->execute()
127.0.0.1 - - [18/Aug/2022:00:11:33 +0000] "GET /login HTTP/1.1" 500 5 "-" "Wget"
#2 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(726): Doctrine\DBAL\Connection->executeQuery('SELECT t0.value...', Array, Array)
#3 /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(193): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#4 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(73): Doctrine\ORM\EntityRepository->findOneBy(Array)
#5 /var/www/wallabag" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
```

### Setting up the database
Now I run this command:
`docker exec -t wallabag /var/www/wallabag/bin/console wallabag:install --env=prod --no-interaction`

The output of which gives me only green checkmarks! I restart all containers:
`docker restart wallabag wallabag_db wallabag_redis`.

Let's look at the `wallabag_db` container logs:
```
2022-08-18 00:18:35+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.5+maria~focal started.
2022-08-18 00:18:36+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2022-08-18 00:18:36+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.5+maria~focal started.
2022-08-18  0:18:36 0 [Note] mariadbd (server 10.6.5-MariaDB-1:10.6.5+maria~focal) starting as process 1 ...
2022-08-18  0:18:36 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-08-18  0:18:36 0 [Note] InnoDB: Number of pools: 1
2022-08-18  0:18:36 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-08-18  0:18:36 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-08-18  0:18:36 0 [Note] InnoDB: Using Linux native AIO
2022-08-18  0:18:36 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-08-18  0:18:36 0 [Note] InnoDB: Completed initialization of buffer pool
2022-08-18  0:18:39 0 [Note] InnoDB: 128 rollback segments are active.
2022-08-18  0:18:39 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-08-18  0:18:39 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-08-18  0:18:40 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-08-18  0:18:40 0 [Note] InnoDB: 10.6.5 started; log sequence number 1168952; transaction id 1134
2022-08-18  0:18:40 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-08-18  0:18:40 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2022-08-18  0:18:40 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2022-08-18  0:18:40 0 [Note] Server socket created on IP: '0.0.0.0'.
2022-08-18  0:18:40 0 [Note] Server socket created on IP: '::'.
2022-08-18  0:18:41 0 [Warning] 'proxies_priv' entry '@% root@2a5df0a4abe1' ignored in --skip-name-resolve mode.
2022-08-18  0:18:42 0 [Note] InnoDB: Buffer pool(s) load completed at 220818  0:18:42
2022-08-18  0:18:43 0 [Note] mariadbd: ready for connections.
Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2022-08-18  0:18:43 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.25.0.6' (This connection closed normally without authentication)
2022-08-18  0:18:55 6 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-08-18  0:19:15 7 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-08-18  0:19:35 10 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

And now at the `wallabag` container logs:
```
Starting provisioner...
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3.9, but future installation of another Python
interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible-
core/2.11/reference_appendices/interpreter_discovery.html for more information.
Provisioner finished.
127.0.0.1 - - [18/Aug/2022:00:19:33 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:19:34 +0000] "GET /login HTTP/1.1" 200 5598 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:20:34 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:20:35 +0000] "GET /login HTTP/1.1" 200 5599 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:21:35 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:21:36 +0000] "GET /login HTTP/1.1" 200 5599 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:22:36 +0000] "GET / HTTP/1.1" 302 346 "-" "Wget"
127.0.0.1 - - [18/Aug/2022:00:22:36 +0000] "GET /login HTTP/1.1" 200 5599 "-" "Wget"
```

### Conclusions
My browser still doesn't show anything when I go to yadayada.domain.tld, and the wallabag container doesn't seem to respond to these requests either. I have no idea what to do anymore! If anyone has an idea, I would love to hear it. All the best.

#Edit: I made a mistake setting up the DNS (which is hosted at Cloudflare). Now that that is fixed, the page yadayada.domain.tld gives me an Error 525 SSL Handshake failed.

**Comment by kromsam** [comment]
The issue has been solved. There was an issue with Let's Encrypt and Cloudflare. I started using the dnsChallenge with Cloudflare as the provider.
