### ISSUE TITLE
v2.6.1 upgrade issue

### ISSUE THREAD

**Issue by mattconnell** [wallabag/docker#337]
## Observed behavior

I upgraded the container and restarted it, and something appears to have gone wrong.  I can no longer log in; the error I get is `Authentication request could not be processed due to a system problem`.  Watching the container's logs, there's no indication of a problem; all of the logged requests return 200.

When I try to connect with the Android application, at least I get a stack trace...

<details>
  <summary>Stack trace</summary>
Server error
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
Stacktrace:
wallabag.apiwrapper.exceptions.UnsuccessfulResponseException: HTTP response: 500 Internal Server Error
 at wallabag.apiwrapper.WallabagService.checkResponse(WallabagService.java:1525)
 at wallabag.apiwrapper.WallabagService.checkResponseBody(WallabagService.java:1503)
 at wallabag.apiwrapper.WallabagService.execAndCheckBody(WallabagService.java:1499)
 at wallabag.apiwrapper.WallabagService.lambda$getArticles$0$WallabagService(WallabagService.java:218)
 at wallabag.apiwrapper.-$$Lambda$WallabagService$PrzoUvX9wnRBX2jTxVqPJ-eD3zU.run(Unknown Source:4)
 at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:140)
 at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:133)
 at wallabag.apiwrapper.NotFoundPolicy.call(NotFoundPolicy.java:128)
 at wallabag.apiwrapper.WallabagService.getArticles(WallabagService.java:218)
 at wallabag.apiwrapper.ArticlesQueryBuilder.execute(ArticlesQueryBuilder.java:282)
 at wallabag.apiwrapper.ArticlesPageIterator.hasNext(ArticlesPageIterator.java:80)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.performUpdate(ArticleUpdater.java:183)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdater.update(ArticleUpdater.java:127)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.updateArticles(ArticleUpdateWorker.java:77)
 at fr.gaulupeau.apps.Poche.service.workers.ArticleUpdateWorker.update(ArticleUpdateWorker.java:37)
 at fr.gaulupeau.apps.Poche.service.tasks.UpdateArticlesTask.run(UpdateArticlesTask.java:17)
 at fr.gaulupeau.apps.Poche.service.tasks.ActionRequestTask.run(ActionRequestTask.java:25)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$0cveUIqKhxWljSld0gpOhfhYfj0.run(Unknown Source:2)
 at fr.gaulupeau.apps.Poche.service.TaskService.run(TaskService.java:162)
 at fr.gaulupeau.apps.Poche.service.TaskService.lambda$PgumDII_lptJcUDKRD70B1M_ER8(Unknown Source:0)
 at fr.gaulupeau.apps.Poche.service.-$$Lambda$TaskService$PgumDII_lptJcUDKRD70B1M_ER8.run(Unknown Source:2)
 at java.lang.Thread.run(Thread.java:1012)
</details>

After the first run on 2.6.1, I see the same behavior when I start up the 2.5.4 container, so whatever broke is persistent.

I don't see any information in the logs for the container, so I'm not sure what to look at.  Did I miss/flub a database upgrade or something?

## Metadata

Install source: docker [wallabag/wallabag](https://hub.docker.com/r/wallabag/wallabag)

Database back-end: Postgresql

Using nginx as a reverse proxy for TLS and all that good stuff.

Docker run command:

```sh
docker run -d \
    --name "wallabag" \
    --restart=unless-stopped \
    -p 20002:80 \
    -e SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql \
    -e SYMFONY__ENV__DATABASE_HOST=172.17.0.1 \
    -e SYMFONY__ENV__DATABASE_PORT=5432 \
    -e SYMFONY__ENV__DATABASE_NAME=wallabag \
    -e SYMFONY__ENV__DATABASE_USER=wallabag \
    -e SYMFONY__ENV__DATABASE_PASSWORD=redacted \
    -e SYMFONY__ENV__DOMAIN_NAME="https://wallabag.example.com" \
    "wallabag/wallabag"
```

**Comment by j0k3r** [comment]
Could you run without `-d` to have log and see what's going wrong?

**Comment by mattconnell** [comment]
Here's what I got. Nothing jumped out to me as being obviously wrong.

```
Starting wallabag ...
Waiting for database ...
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/compiler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/consistency is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/event is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/exception is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/file is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/iterator is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/math is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/protocol is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/regex is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ruler is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/stream is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/ustring is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/visitor is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/zformat is abandoned, you should avoid using it. No replacement was suggested.
Package lexik/form-filter-bundle is abandoned, you should avoid using it. Use spiriitlabs/form-filter-bundle instead.
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package true/punycode is abandoned, you should avoid using it. No replacement was suggested.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class SimpleHtmlDom\simple_html_dom_node located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
Class SimpleHtmlDom\simple_html_dom located in ./vendor/mgargano/simplehtmldom/src/simple_html_dom.php does not comply with psr-0 autoloading standard. Skipping.
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> bin/console cache:clear --no-warmup

 // Clearing the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

> bin/console assets:install web --symlink --relative

 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------
      Bundle                   Method / Error
 --- ------------------------ ------------------
  ✔   NelmioApiDocBundle       relative symlink
  ✔   CraueConfigBundle        relative symlink
  ✔   BabDevPagerfantaBundle   relative symlink
  ✔   FOSJsRoutingBundle       relative symlink
 --- ------------------------ ------------------

 [OK] All assets were successfully installed.

wallabag is ready!

```

**Comment by mattconnell** [comment]
The directory `/var/www/wallabag/var/logs/` has no log files in it.

**Comment by j0k3r** [comment]
This is weird, if you tried to access the UI, some logs must be present in that folder.
Anyway, did you run migration after the update?
If not could you run them?
https://github.com/wallabag/docker#upgrading

**Comment by mainzelM** [comment]
I had the same issue. Running the migration command fixed it. Thanks for the fast feedback and the new version!

**Comment by mattconnell** [comment]
The migration appears to have resolved my issue as well.  Apologies for wasting your time/attention.

Embarrassingly, I was prompted to upgrade the container based on seeing the release notes in my RSS feeds, and yet somehow completely disregarded the _first numbered point_, of "don't forget to [run migration](https://github.com/wallabag/docker#upgrading) otherwise your wallabag won't work"

No excuses there, I just didn't do what was needed.  Sometimes we all need to "read the friendly manual", so to speak.
