### ISSUE TITLE
Storing config on a volume creates errors

### ISSUE THREAD

**Issue by shageman** [wallabag/docker#37]
I am trying to store the wallabag config outside the container by mounting a volume:
~~~~~~~~
-v ./volumes/wallabag-server/config:/var/www/wallabag/app/config
~~~~~~~~
As soon as I do, the server can not start up anymore. It errors out with the following:
~~~~~~~~
wallabag-server    | 2016/11/28 19:45:02 [error] 255#255: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: The file "/var/www/wallabag/app/config/config_prod.yml" does not exist. in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Config/FileLocator.php:44
wallabag-server    | Stack trace:
wallabag-server    | #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Config/FileLocator.php(54): Symfony\Component\Config\FileLocator->locate('/var/www/wallab...', NULL, true)
wallabag-server    | #1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(66): Symfony\Component\HttpKernel\Config\FileLocator->locate('/var/www/wallab...')
wallabag-server    | #2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/DelegatingLoader.php(45): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/var/www/wallab...', NULL)
wallabag-server    | #3 /var/www/wallabag/app/AppKernel.php(72): Symfony\Component\Config\Loader\DelegatingLoader->load('/var/www/wallab...')
wallabag-server    | #4 /var/www/wallabag/var/bootstrap.php.cache(1673): AppKernel->registerContai" while reading response header from upstream, client: ::ffff:172.21.0.4, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.cupreo.us"
wallabag-server    | ::ffff:172.21.0.4 - - [28/Nov/2016:19:45:02 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"
~~~~~~~~

The server is creating `paramaters.yml` correctly - no other files are being created...

Any ideas are much appreciated!

**Comment by shageman** [comment]
Cleaning up old unanswered issues.
