### ISSUE TITLE
Symfony: Could not gather sufficient random data

### ISSUE THREAD

**Issue by Miladiir** [wallabag/docker#64]
Getting this on a fresh Debian jessie docker CE install. Other containers work fine.
uname -a: `Linux Debian-87-jessie-64-minimal 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux`

```
sudo docker run -v /opt/wallabag:/var/www/wallabag/data -p 80:80 wallabag/wallabag
Unable to find image 'wallabag/wallabag:latest' locally
latest: Pulling from wallabag/wallabag
627beaf3eaaf: Pull complete
b04957b0e1ca: Pull complete
f8a4b6141f4a: Pull complete
76a85e86b34a: Pull complete
Digest: sha256:a6589cf54db8b2c0f6dff80bce5e9177cf0a05cbc826b1b9d586b33a4d3e89da
Status: Downloaded newer image for wallabag/wallabag:latest
Starting provisioner...
Provisioner finished.
::ffff:217.228.111.230 - - [08/May/2017:07:11:12 +0000] "GET / HTTP/1.1" 302 208 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
::ffff:217.228.111.230 - - [08/May/2017:07:11:12 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
2017/05/08 07:11:12 [error] 308#308: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php:46
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php(46): random_bytes(32)
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php(57): Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator->generateToken()
#2 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php(53): Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('authenticate')
#3 [internal function]: FOS\UserBundle\Controller\SecurityController->loginAction(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/wallabag/var/cache/prod/classes.php(4651): call_user_func_array(Array, Array)
#5 /var/www/wallabag/var/cache/prod/classes.php(4606): Symfony\C" while reading response header from upstream, client: ::ffff:217.228.111.230, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "176.9.47.51"sudo docker run -v /opt/wallabag:/var/www/wallabag/data -p 80:80 wallabag/wallabag
Unable to find image 'wallabag/wallabag:latest' locally
latest: Pulling from wallabag/wallabag
627beaf3eaaf: Pull complete
b04957b0e1ca: Pull complete
f8a4b6141f4a: Pull complete
76a85e86b34a: Pull complete
Digest: sha256:a6589cf54db8b2c0f6dff80bce5e9177cf0a05cbc826b1b9d586b33a4d3e89da
Status: Downloaded newer image for wallabag/wallabag:latest
Starting provisioner...
Provisioner finished.
--REDACTED-- - - [08/May/2017:07:11:12 +0000] "GET / HTTP/1.1" 302 208 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
--REDACTED-- - - [08/May/2017:07:11:12 +0000] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
2017/05/08 07:11:12 [error] 308#308: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php:46
Stack trace:
#0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php(46): random_bytes(32)
#1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php(57): Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator->generateToken()
#2 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php(53): Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('authenticate')
#3 [internal function]: FOS\UserBundle\Controller\SecurityController->loginAction(Object(Symfony\Component\HttpFoundation\Request))
#4 /var/www/wallabag/var/cache/prod/classes.php(4651): call_user_func_array(Array, Array)
#5 /var/www/wallabag/var/cache/prod/classes.php(4606): Symfony\C" while reading response header from upstream, client: --REDACTED--, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "--REDACTED--"
```

**Comment by Miladiir** [comment]
See : https://github.com/wallabag/docker/issues/57

I cannot read apparently.
